### ISSUE TITLE
semi-supervised regression

### ISSUE THREAD

**Issue by rojinsafavi** [probtorch/probtorch#42]
Hello,
I was wondering if you can provide the code for semi-supervised regression that you used in the paper?
Thanks,

**Comment by iffsid** [comment]
Thanks for getting in touch!

The code for the faces experiments is in a private repo, but it's not been updated in more than a year, and relies on an old version of both probtorch (579de6) _and_ pytorch (0.3.1 iirc).
Rather than updating stuff for public release now, I figured it might be faster to just bundle the files up and provide a link to download them from:

   [nips-experiments-master.zip](iffsid.com/nips-experiments-master.zip)

Note that in addition to the source for the faces experiment, as well as an ipython notebook for it, the zip file includes the 'raw' data---already pre-processed by Jampani et.al. as well as scripts to adapt it to our model.
